app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::controller('password', 'RemindersController');


/**
 * -------------------------------------------------------
 *  Admin routes
 *  ------------------------------------------------------
 */
Route::group(array('prefix' => 'admin'), function() 
{

    # Authentication routes
    Route::get('login', array('as' => 'login.get', 'uses' => 'AuthController@showLogin')); 
    Route::post('login', array('as' => 'login.post', 'uses' => 'AuthController@authenticateUser'));
    Route::get('logout', array('as' => 'logout.get', 'uses' => 'AuthController@logoutUser'));

    # Routes where authentication is needed
    Route::group(array('before' => 'auth'), function() 
    {
        Route::get('/', 'PageController@index');    
    
        # Page management routes
        Route::resource('page', 'PageController');

        # User management routes
        Route::get('user', array('as' => 'user.index', 'uses' => 'UserController@index'));
        Route::get('user/edit/{id}',  array('as' => 'user.edit', 'uses' => 'UserController@edit'));
        Route::post('user/edit/{id}',  array('as' => 'user.update', 'uses' => 'UserController@update'));
        Route::get('user/create',  array('as' => 'user.create', 'uses' => 'UserController@create'));
        Route::post('user/store',  array('as' => 'user.store', 'uses' => 'UserController@store'));
        
        # Roles management routes
        Route::get('roles', array(
            'as' => 'role.index',
            'uses' => 'RoleController@index',
        ));
        Route::get('roles/create', array(
            'as' => 'role.create',
            'uses' => 'RoleController@create',
        ));
        Route::post('roles/create', array(
            'as' => 'role.store',
            'uses' => 'RoleController@store',
        ));
        Route::get('roles/edit/{id}', array(
            'as' => 'role.edit',
            'uses' => 'RoleController@edit',
        ));
        Route::post('roles/edit/{id}', array(
            'as' => 'role.update',
            'uses' => 'RoleController@update',
        ));

        # Routes project management
        Route::get('projects', array('as' => 'project.index', 'uses' => 'ProjectController@index'));
        Route::get('projects/create', array('as' => 'project.create', 'uses' => 'ProjectController@create'));
        Route::post('projects/store', array('as' => 'project.store', 'uses' => 'ProjectController@store'));
        Route::get('projects/edit/{id}', array('as' => 'project.edit', 'uses' => 'ProjectController@edit'));
        Route::post('projects/update/{id}', array('as' => 'project.update', 'uses' => 'ProjectController@update'));
        Route::post('projects/upload', array('as' => 'project.upload', 'uses' => 'ProjectController@uploadImage'));
    });       

});




/**
 * -------------------------------------------------------
 *  Frontend routes
 *  ------------------------------------------------------
 */
Route::get('/{slug}', function($slug)
{
    $page = Page::where('slug',$slug)->first();

    if (!$page) App::abort(404, $slug.' was not found. Next time better');

    return View::make('frontend.content', array('page' => $page));
});


Route::get('/', function() 
{
    return View::make('hello');
});


App::missing(function($exception)
{
    return Response::view('404', array(), 404);
});

app/views/backend/page/create.blade.php
@extends('backend.base')

@section('content')

<div class="block-wrapper">
    
    <div class="block-head">
        <h4>ADD PAGE</h4>
        <div class="btn-group pull-right">
            <a href="{{ route('admin.page.index') }}" class="btn"><b>cancel</b></a>
        </div>
    </div>
    
    <div class="block-body">
        
        {{ Form::open(array('route' => 'admin.page.store', 'class' => 'form')) }}

        <ul class="nav nav-tabs" id="page-container">
            <li><a href="#page-details">Page details</a></li>
            <li><a href="#page-content">Content</a></li>
            <li><a href="#page-meta">Meta data</a></li>
        </ul>

        <div class="tab-content">

            <!-- #page-details -->

            <div class="tab-pane" id="page-details">

                <div class="contol-group">
                    {{ Form::label('title','Title', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::input('text', 'title') }}
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('slug','Slug', array('class' => 'control-label')) }}
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on">{{ Request::root() }}/</span>
                            {{ Form::input('text', 'slug') }}
                        </div>                        
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('published','Published', array('class' => 'control-label')) }}
                    <div class="controls">
                        <label class="radio inline">
                            {{ Form::radio('published', '1'); }} Yes
                        </label>
                        <label class="radio inline">
                            {{ Form::radio('published', '0', true); }} No
                        </label>                        
                    </div>           
                </div>

            </div><!-- end #page-details -->

            <!-- #page-content -->

            <div class="tab-pane" id="page-content">
                <div class="contol-group">
                    <label class="control-label">Content</label>
                    <div class="controls">
                        {{ Form::textarea('content', '', array('class' => 'content')) }}
                    </div>           
                </div>
            </div><!-- end #page-content -->

            <!-- #page-meta -->

            <div class="tab-pane" id="page-meta">

                <div class="contol-group">
                    {{ Form::label('meta_keywords','Meta keywords', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::input('text', 'meta_keywords') }}                                
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('meta_desc','Meta description', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::textarea('meta_desc', '') }}                                
                    </div>           
                </div> <hr>
                
            </div>

        </div>
        
        <div class="form-actions">
            <input type="submit" name="save" value="Pagina toevoegen" class="btn btn-primary">
        </div>

        {{ Form::close() }}
        
    </div>
    
</div>
    
@stop


@section('javascripts')

    @parent

    <script type="text/javascript" src="/assets/js/jquery.slugify.js"></script>

    @include('backend._partial.tinymce_script')

@stop

app/views/backend/page/edit.blade.php
@extends('backend.base')

@section('content')

<div class="block-wrapper">
    
    <div class="block-head">
        <h4>EDIT PAGE: {{ $page->title }}</h4>
        <div class="pull-right">            
            <a href="{{ route('admin.page.index') }}" class="btn"><b>cancel</b></a>
        </div>
    </div>
    
    <div class="block-body">
        
        {{ Form::model($page, ['method' => 'PUT', 'route' => ['admin.page.update', $page->id], 'class' => 'form']) }}

        <ul class="nav nav-tabs" id="page-container">
            <li><a href="#page-details">Page details</a></li>
            <li><a href="#page-content">Content</a></li>
            <li><a href="#page-meta">Meta data</a></li>
        </ul>

        <div class="tab-content">

            <!-- #page-details -->

            <div class="tab-pane" id="page-details">

                <div class="contol-group">
                    {{ Form::label('title','Title', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::input('text', 'title') }}
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('slug','Slug', array('class' => 'control-label')) }}
                    <div class="controls">
                        <div class="input-prepend">
                            <span class="add-on">{{ Request::root() }}/</span>
                            {{ Form::input('text', 'slug') }}
                        </div>                        
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('published','Published', array('class' => 'control-label')) }}
                    <div class="controls">
                        <label class="radio inline">
                            {{ Form::radio('published', '1'); }} Yes
                        </label>
                        <label class="radio inline">
                            {{ Form::radio('published', '0', true); }} No
                        </label>
                        
                    </div>           
                </div>

            </div><!-- end #page-details -->

            <!-- #page-content -->

            <div class="tab-pane" id="page-content">
                <div class="contol-group">
                    <label class="control-label">Content</label>
                    <div class="controls">
                        {{ Form::textarea('content', $page->content, array('class' => 'content')) }}
                    </div>           
                </div>
            </div><!-- end #page-content -->

            <!-- #page-meta -->

            <div class="tab-pane" id="page-meta">

                <div class="contol-group">
                    {{ Form::label('meta_keywords','Meta keywords', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::input('text', 'meta_keywords') }}                                
                    </div>           
                </div> <hr>

                <div class="contol-group">
                    {{ Form::label('meta_desc','Meta description', array('class' => 'control-label')) }}
                    <div class="controls">
                        {{ Form::textarea('meta_desc') }}                                
                    </div>           
                </div> <hr>
                
            </div> <!-- end #page-meta -->

        </div>
        
        <div class="form-actions">
            <input type="submit" name="save" value="SAVE" class="btn btn-primary">
        </div>

        {{ Form::close() }}
        
    </div>
    
</div>
    
@stop

@section('javascripts')
    @parent   
    @include('backend._partial.tinymce_script')
    @include('backend._partial.notification')
@stop

app/views/backend/page/list.blade.php
@extends('backend.base')

@section('content')

<div class="block-wrapper">

    <div class="block-head">
        <h4>Pages</h4>
        <div class="btn-group pull-right">
            <a href="{{ URL::Route('admin.page.create') }}" class="btn"><i class="icon icon-plus"></i></a>
        </div>
    </div>

    <div class="block-body">

        <table class="table table-hover my-table">
            
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Created at</th>
                    <th>Published</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($pages as $page)
                <tr>
                    <td>{{ $page->id }}</td>
                    <td><a href="{{ route('admin.page.edit', $page->id) }}">{{ $page->title }}</a></td>
                    <td>{{ $page->slug }}</a></td>
                    <td>{{ $page->created_at }}</td>
                    <td>{{ display_status($page->published) }}</td>
                    <td class="text-right">
                        <a href="{{ route('admin.page.edit', $page->id) }}" class="btn btn-warning"><i class="icon-edit  icon-white"></i></a>                    
                        {{ Form::open(['action' => ['PageController@destroy', $page->id], 'method' => 'DELETE', 'class' => 'delete']) }}
                        <button class="btn btn-danger delete"
                                {{-- href="{{ route('admin.page.edit', $page->id) }}" --}}
                                ><i class="icon-trash icon-white"></i></button>
                        {{ Form::close() }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

</div>

@stop

@section('javascripts')
    @parent
    @include('backend._partial.notification')    
@stop